[tool.poetry]
name = "shibumi-store"
version = "0.1.0"
description = ""
authors = ["Valentyn Malenchak <valentyn17@gmail.com>"]
readme = "README.md"
packages = [{include = "shibumi_store"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.109.2"
uvicorn = {extras = ["standard"], version = "0.27.1"}
pytest = "8.0.0"
invoke = "2.2.0"
motor = "3.3.2"
python-jose = {extras = ["cryptography"], version = "3.3.0"}
arrow = "1.3.0"
httpx = "0.26.0"
python-multipart = "0.0.9"
passlib = "1.7.4"
types-passlib = "1.7.7.20240106"
types-python-jose = "3.3.4.20240106"
injector = "0.21.0"
pytest-asyncio = "0.23.5"
motor-types = "1.0.0b4"
pytest-cov = "4.1.0"
pydantic = {extras = ["email"], version = "2.6.1"}
phonenumbers = "8.13.30"
pydantic-extra-types = "2.5.0"
mongodb-migrations = "1.3.0"
freezegun = "1.4.0"
redis = "5.0.1"
sendgrid = "6.11.0"
tenacity = "8.2.3"


[tool.poetry.group.dev.dependencies]
mypy = "1.8.0"
ruff = "0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
