[tool.poetry]
name = "fastapi-shop"
version = "0.1.0"
description = ""
authors = ["Valentyn Malenchak <valentyn17@gmail.com>"]
readme = "README.md"
packages = [{include = "fastapi_shop"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.109.0"
uvicorn = {extras = ["standard"], version = "0.25.0"}
pytest = "7.4.4"
invoke = "2.2.0"
motor = "3.3.2"
python-jose = {extras = ["cryptography"], version = "3.3.0"}
arrow = "1.3.0"
httpx = "0.26.0"
python-multipart = "0.0.6"
passlib = "1.7.4"
types-passlib = "1.7.7.13"
types-python-jose = "3.3.4.8"
injector = "0.21.0"
pytest-asyncio = "0.23.3"
motor-types = "1.0.0b4"
pytest-cov = "4.1.0"
pydantic = {extras = ["email"], version = "2.5.3"}
phonenumbers = "8.13.27"
pydantic-extra-types = "2.4.0"
mongodb-migrations = "1.3.0"
freezegun = "1.4.0"


[tool.poetry.group.dev.dependencies]
mypy = "1.8.0"
ruff = "0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
