[tool.poetry]
name = "shibumi-store"
version = "0.1.0"
description = "The 'Shibumi Store' backend project is a small e-commerce solution that provides a seamless and efficient shopping experience."
authors = ["Valentyn Malenchak <valentyn17@gmail.com>"]
readme = "README.md"
packages = [{include = "shibumi_store"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.0"
uvicorn = {extras = ["standard"], version = "0.31.0"}
pytest = "8.3.3"
invoke = "2.2.0"
motor = "3.6.0"
arrow = "1.3.0"
httpx = "0.27.2"
python-multipart = "0.0.12"
injector = "0.22.0"
pytest-asyncio = "0.24.0"
motor-types = "1.0.0b4"
pytest-cov = "5.0.0"
pydantic = {extras = ["email"], version = "2.9.2"}
phonenumbers = "8.13.47"
pydantic-extra-types = "2.9.0"
mongodb-migrations = "1.3.1"
redis = "5.1.1"
sendgrid = "6.11.0"
tenacity = "9.0.0"
pyjwt = "2.9.0"
argon2-cffi = "23.1.0"


[tool.poetry.group.dev.dependencies]
mypy = "1.11.2"
ruff = "0.6.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
