[tool.poetry]
name = "shibumi-store"
version = "0.1.0"
description = "The 'Shibumi Store' backend project is a small e-commerce solution that provides a seamless and efficient shopping experience."
authors = ["Valentyn Malenchak <valentyn17@gmail.com>"]
readme = "README.md"
packages = [{include = "shibumi_store"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.111.0"
uvicorn = {extras = ["standard"], version = "0.30.1"}
pytest = "8.2.2"
invoke = "2.2.0"
motor = "3.5.1"
arrow = "1.3.0"
httpx = "0.27.0"
python-multipart = "0.0.9"
injector = "0.22.0"
pytest-asyncio = "0.23.7"
motor-types = "1.0.0b4"
pytest-cov = "5.0.0"
pydantic = {extras = ["email"], version = "2.8.2"}
phonenumbers = "8.13.40"
pydantic-extra-types = "2.9.0"
mongodb-migrations = "1.3.1"
freezegun = "1.5.1"
redis = "5.0.7"
sendgrid = "6.11.0"
tenacity = "8.5.0"
pyjwt = "2.8.0"
argon2-cffi = "23.1.0"


[tool.poetry.group.dev.dependencies]
mypy = "1.10.1"
ruff = "0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
